#!/usr/bin/env python3
"""
Regenerate the AUTO block in framework/skill-map.md from SKILL.md frontmatter.

Markers (framework/skill-anatomy.md §Generator-Output-Strategie):
  <!-- SKILL-MAP-AUTO-START -->
  ...
  <!-- SKILL-MAP-AUTO-END -->

Skills under skills/_archived/ are excluded.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore

AUTO_START = "<!-- SKILL-MAP-AUTO-START -->"
AUTO_END = "<!-- SKILL-MAP-AUTO-END -->"


def repo_root(start: Path) -> Path:
    cur = start.resolve()
    for parent in [cur] + list(cur.parents):
        if (parent / "framework").is_dir():
            return parent
    return start.resolve()


def extract_frontmatter(text: str) -> dict | None:
    # Accept UTF-8 BOM-prefixed markdown files.
    text = text.lstrip("\ufeff")
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    if yaml is None:
        return None
    try:
        data = yaml.safe_load(parts[1])
        return data if isinstance(data, dict) else None
    except yaml.YAMLError:
        return None


def classify_skill(name_dir: str, data: dict | None) -> tuple[str, str]:
    """Returns (bucket_key, detail_line)."""
    if not data:
        return ("legacy", f"`{name_dir}` *(YAML parse failed)*")

    inv = data.get("invocation")
    prim = None
    if isinstance(inv, dict):
        prim = inv.get("primary")

    if prim == "user-facing":
        return ("direct", name_dir)
    if prim == "workflow-step":
        return ("workflow", name_dir)
    if prim == "sub-skill":
        return ("workflow", name_dir)
    if prim == "cross-cutting":
        return ("cross", name_dir)
    if prim == "hook":
        return ("hook", name_dir)
    if data.get("disable-model-invocation") is True:
        return ("service", name_dir)

    # Unknown invocation.primary — surface as legacy entry.
    return ("legacy", f"`{name_dir}` *(unknown invocation.primary)*")


def iter_skills(skills_root: Path) -> list[tuple[str, dict | None]]:
    out: list[tuple[str, dict | None]] = []
    if not skills_root.is_dir():
        return out
    for child in sorted(skills_root.iterdir()):
        if not child.is_dir():
            continue
        if child.name.startswith("_"):
            continue
        sf = child / "SKILL.md"
        if not sf.is_file():
            continue
        text = sf.read_text(encoding="utf-8")
        data = extract_frontmatter(text)
        out.append((child.name, data))
    return out


def render_auto_block(skills_root: Path) -> str:
    rows = iter_skills(skills_root)
    buckets: dict[str, list[str]] = {
        "direct": [],
        "workflow": [],
        "service": [],
        "cross": [],
        "hook": [],
        "legacy": [],
    }

    for name_dir, data in rows:
        key, line = classify_skill(name_dir, data)
        if key == "legacy":
            buckets["legacy"].append(line)
        elif key == "direct":
            buckets["direct"].append(f"`{name_dir}`")
        elif key == "workflow":
            buckets["workflow"].append(f"`{name_dir}`")
        elif key == "service":
            buckets["service"].append(f"`{name_dir}`")
        elif key == "cross":
            buckets["cross"].append(f"`{name_dir}`")
        elif key == "hook":
            buckets["hook"].append(f"`{name_dir}`")

    lines = [
        AUTO_START,
        "",
        "Generated by `scripts/generate_skill_map.py` — do not edit manually.",
        "",
        "Canonical for `consistency_check` §Skill-Map; sub-sections derived from `invocation.primary`.",
        "",
        "### Direct-Invokable Capabilities (`invocation.primary: user-facing`)",
        "",
        _comma_join_sorted(buckets["direct"]),
        "",
        "### Workflow-Step / Sub-skill (`workflow-step` | `sub-skill`)",
        "",
        _comma_join_sorted(buckets["workflow"]),
        "",
        "### Service Skills (`disable-model-invocation: true`)",
        "",
        _comma_join_sorted(buckets["service"]),
        "",
        "### Cross-cutting Skills (`cross-cutting`)",
        "",
        _comma_join_sorted(buckets["cross"]),
        "",
        "### Hook-triggered Skills (`hook`)",
        "",
        _comma_join_sorted(buckets["hook"]),
        "",
        "### Unclassified",
        "",
        _comma_join_sorted(buckets["legacy"]) if buckets["legacy"] else "*(none)*",
        "",
        AUTO_END,
    ]
    return "\n".join(lines) + "\n"


def _comma_join_sorted(items: list[str]) -> str:
    if not items:
        return "*(none)*"
    items_sorted = sorted(items, key=lambda s: s.lower())
    return ", ".join(items_sorted)


def replace_auto_section(content: str, new_section: str) -> str | None:
    if AUTO_START not in content or AUTO_END not in content:
        return None
    pattern = re.compile(
        re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END),
        re.DOTALL,
    )
    if not pattern.search(content):
        return None
    return pattern.sub(new_section.strip(), content)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", type=Path, default=None)
    ap.add_argument("--check", action="store_true", help="fail if file would change")
    args = ap.parse_args()
    root = repo_root(args.repo or Path.cwd())
    skills_root = root / "skills"
    map_path = root / "framework" / "skill-map.md"

    if yaml is None:
        print("generate_skill_map: SKIP — PyYAML missing", file=sys.stderr)
        return 0

    if not map_path.is_file():
        print(f"generate_skill_map: missing {map_path}", file=sys.stderr)
        return 1

    new_block = render_auto_block(skills_root)
    body = map_path.read_text(encoding="utf-8")
    merged = replace_auto_section(body, new_block)
    if merged is None:
        print(
            "generate_skill_map: markers not found — insert <!-- SKILL-MAP-AUTO-START/END -->",
            file=sys.stderr,
        )
        return 1

    if args.check:
        if merged != body:
            print("generate_skill_map: drift detected (run without --check)")
            return 1
        print("generate_skill_map: OK (no drift)")
        return 0

    map_path.write_text(merged, encoding="utf-8")
    print(f"generate_skill_map: wrote {map_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
